export const VALUE_CHANGE = "VALUE_CHANGE";
export const ARRAY_VALUE_ADD = "ARRAY_VALUE_ADD";
export const ARRAY_VALUE_CHANGE = "ARRAY_VALUE_CHANGE";
export const ARRAY_VALUE_REMOVE = "ARRAY_VALUE_REMOVE";
